server {
    listen 80;
    server_tokens off;

    location /kittygram/static/ {
        alias /staticfiles/static/;
    }

    location /kittygram/media/ {
        alias /media/;
    }

    location /kittygram/api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $http_host;
    }

    location /kittygram/admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $http_host;
    }

    location = /kittygram {
        return 301 /kittygram/;
    }

    location /kittygram/ {
        alias /staticfiles/;
        index index.html;
        try_files $uri $uri/ =404;
        error_page 404 =200 /kittygram/index.html;
    }

    location / {
        return 404;
    }
}
